LOCAL_PATH := $(call my-dir)

# libNetwork
include $(CLEAR_VARS)

LOCAL_MODULE := LIBARNETWORKAL-prebuilt
LOCAL_SRC_FILES := lib/libarnetworkal.a

include $(PREBUILT_STATIC_LIBRARY)

# WRAPPER_LIB
include $(CLEAR_VARS)

LOCAL_C_INCLUDES:= $(LOCAL_PATH)/include $(LOCAL_PATH)/../libARSAL/include
LOCAL_LDLIBS := -llog
LOCAL_MODULE := libarnetworkal_android
LOCAL_SRC_FILES := ARNETWORKAL_JNIManager.c
LOCAL_CFLAGS := -O0 -g
LOCAL_STATIC_LIBRARIES := LIBARNETWORKAL-prebuilt
LOCAL_SHARED_LIBRARIES := LIBARSAL-prebuilt
include $(BUILD_SHARED_LIBRARY)
